### ISSUE TITLE
vue.runtime error

### ISSUE THREAD

**Issue by charonX** [Tendsty/gooboo#25]
in school features, I encountered an error as follows:

vue.runtime.esm.js:3049 TypeError: e.$vnode.data.staticClass is not iterable
    at fn (PriceTag.vue:1:749)
    at r (vue.runtime.esm.js:2404:41)
    at a.ce [as _t] (vue.runtime.esm.js:2082:13)
    at fn (GoobooTooltip.vue:1:315)
    at Object.r [as activator] (vue.runtime.esm.js:2404:41)
    at A (helpers.ts:413:28)
    at a.genActivator (index.ts:85:20)
    at a.render (VTooltip.ts:229:12)
    at Pe.t._render (vue.runtime.esm.js:2684:28)
    at a.s (vue.runtime.esm.js:3875:27)

**Comment by DreamNya** [comment]
![4264e97ad525775b5d46d15b31267be9](https://github.com/Tendsty/gooboo/assets/34838824/39c13550-c9dd-41e0-a3c5-bdaec0271ef8)
Same error occurs in the farm. Maybe some elements are missing
